/*
  # Add Products for Joint & Bone Health and Gut Health Categories

  1. New Products
    - 5 Joint & Bone Health: Move Free Advanced, Osteo Bi-Flex, Thorne Glucosamine & Chondroitin, NOW Hyaluronic Acid, Garden of Life mykind Calcium
    - 5 Gut Health & Probiotics: Seed DS-01 Synbiotic, Culturelle Digestive Health, Align Probiotic, Garden of Life Dr. Formulated, Ritual Synbiotic+
*/

-- Joint & Bone Health
INSERT INTO products (name, brand, slug, description, long_description, category_id, image_url, price_min, price_max, rating, affiliate_link, affiliate_link_official, key_ingredients, pros, cons, best_for, third_party_tested) VALUES
('Move Free Advanced', 'Schiff', 'move-free-advanced', 'A joint health formula combining glucosamine, chondroitin, hyaluronic acid, and Uniflex (FruiteX-B) for comprehensive cartilage, bone, and joint support.', 'Move Free Advanced is one of America''s best-selling joint supplements. It combines four joint-supporting ingredients: glucosamine for cartilage building, chondroitin for cushioning, hyaluronic acid for lubrication, and patented Uniflex for bone strength.', '02a22e67-4d99-4637-8270-69455889c8a7', 'https://m.media-amazon.com/images/I/71-fKDCNxrL._AC_SL1500_.jpg', 18, 35, 4.6, 'https://www.amazon.com/s?k=Move+Free+Advanced', NULL, ARRAY['Glucosamine', 'Chondroitin', 'Hyaluronic Acid', 'FruiteX-B (Uniflex)'], ARRAY['Comprehensive 4-ingredient formula', 'Widely available and affordable', 'Trusted Schiff brand', 'Good for daily maintenance'], ARRAY['Large tablets', 'Results take 4-8 weeks', 'Contains shellfish (glucosamine)', 'Not suitable for vegans'], 'Adults with daily joint stiffness', false),

('Triple Strength', 'Osteo Bi-Flex', 'osteo-bi-flex-triple-strength', 'A triple-action joint health supplement with glucosamine, vitamin D, and the patented 5-Loxin advanced boswellia extract for joint comfort within 7 days.', 'Osteo Bi-Flex Triple Strength is one of the most recognized joint supplements. Its star ingredient is 5-Loxin, a patented boswellia serrata extract clinically shown to improve joint comfort in as little as 7 days.', '02a22e67-4d99-4637-8270-69455889c8a7', 'https://m.media-amazon.com/images/I/71t9zqnMCML._AC_SL1500_.jpg', 16, 28, 4.5, 'https://www.amazon.com/s?k=Osteo+Bi-Flex+Triple+Strength', NULL, ARRAY['Glucosamine HCl', '5-Loxin Boswellia', 'Vitamin D3', 'Joint Shield'], ARRAY['Results possible in 7 days', 'Patented 5-Loxin ingredient', 'Affordable daily cost', 'Includes vitamin D3'], ARRAY['Only 1 tablet per day limits dosing flexibility', 'Contains shellfish', 'Less comprehensive than premium options', 'Proprietary Joint Shield blend'], 'Those wanting fast-acting joint relief', false),

('Glucosamine & Chondroitin', 'Thorne', 'thorne-glucosamine-chondroitin', 'A practitioner-grade joint supplement combining glucosamine sulfate and chondroitin sulfate in optimal ratios, free from shellfish-derived ingredients.', 'Thorne delivers their characteristic purity to joint health. Their Glucosamine & Chondroitin uses non-shellfish glucosamine (corn-derived) and pharmaceutical-grade chondroitin in the clinically studied 2:1 ratio.', '02a22e67-4d99-4637-8270-69455889c8a7', 'https://m.media-amazon.com/images/I/71TCoaW5s2L._AC_SL1500_.jpg', 30, 42, 4.7, 'https://www.amazon.com/s?k=Thorne+Glucosamine+Chondroitin', NULL, ARRAY['Glucosamine Sulfate', 'Chondroitin Sulfate', 'Non-Shellfish Source'], ARRAY['Non-shellfish glucosamine (corn-derived)', 'Practitioner-grade purity', 'Optimal 2:1 ratio', 'NSF Certified for Sport'], ARRAY['Premium pricing', '3 capsules per serving', 'Slower acting than anti-inflammatories', 'Basic two-ingredient formula'], 'Shellfish-allergic individuals and athletes', true),

('Hyaluronic Acid 100mg', 'NOW Foods', 'now-hyaluronic-acid', 'A high-dose hyaluronic acid supplement for joint lubrication, skin hydration, and eye health at an affordable price from a trusted GMP-certified brand.', 'NOW Foods Hyaluronic Acid provides 100mg of this naturally occurring molecule that acts as a lubricant and cushion for joints, skin, and eyes. As we age, our natural HA production declines, making supplementation beneficial.', '02a22e67-4d99-4637-8270-69455889c8a7', 'https://m.media-amazon.com/images/I/71e4H8xbhfL._AC_SL1500_.jpg', 12, 22, 4.5, 'https://www.amazon.com/s?k=NOW+Hyaluronic+Acid+100mg', NULL, ARRAY['Hyaluronic Acid 100mg', 'L-Proline', 'Alpha Lipoic Acid', 'Grape Seed Extract'], ARRAY['Affordable joint and skin support', 'Multi-benefit (joints, skin, eyes)', 'Added synergistic ingredients', 'GMP certified'], ARRAY['Oral HA absorption debated', 'Benefits take weeks to notice', 'Capsule form only', 'Not as directly effective as injected HA'], 'Those wanting joint lubrication and skin hydration', true),

('mykind Organics Plant Calcium', 'Garden of Life', 'garden-of-life-calcium', 'A whole-food organic plant calcium derived from red marine algae, with vitamin D3 and K2 for optimal calcium absorption and bone density support.', 'Garden of Life mykind Organics Plant Calcium is sourced from organic Lithothamnion red algae, not limestone or chalk. Paired with organic vitamins D3 and K2 to ensure calcium goes to bones rather than arteries.', '02a22e67-4d99-4637-8270-69455889c8a7', 'https://m.media-amazon.com/images/I/71OMtRFj2nL._AC_SL1500_.jpg', 25, 38, 4.5, 'https://www.amazon.com/s?k=Garden+of+Life+mykind+Organics+Plant+Calcium', NULL, ARRAY['Organic Plant Calcium', 'Vitamin D3', 'Vitamin K2', 'Red Marine Algae'], ARRAY['Whole food plant-sourced calcium', 'Vegan-friendly', 'Includes D3 and K2 for absorption', 'USDA Organic'], ARRAY['3 tablets per serving', 'Lower calcium dose than synthetics', 'More expensive than regular calcium', 'Large tablet size'], 'Vegans and whole-food supplement users', true);

-- Gut Health & Probiotics
INSERT INTO products (name, brand, slug, description, long_description, category_id, image_url, price_min, price_max, rating, affiliate_link, affiliate_link_official, key_ingredients, pros, cons, best_for, third_party_tested) VALUES
('DS-01 Daily Synbiotic', 'Seed', 'seed-ds-01', 'A next-generation synbiotic combining 24 clinically studied probiotic strains with a prebiotic outer capsule. The most science-forward probiotic on the market.', 'Seed DS-01 represents the cutting edge of gut health supplementation. Its 24 strain, 53.6 billion AFU formulation uses a patented ViaCap delivery system that protects probiotics through stomach acid for targeted release.', '840cca75-0ebc-44a2-819f-212cd78a1464', 'https://m.media-amazon.com/images/I/51-vHzD9oJL._AC_SL1000_.jpg', 49, 49, 4.7, 'https://www.amazon.com/s?k=Seed+DS-01+Synbiotic', 'https://seed.com', ARRAY['24 Probiotic Strains', '53.6 Billion AFU', 'Prebiotic Outer Capsule', 'Patented ViaCap Delivery'], ARRAY['Most studied strains available', 'Acid-resistant delivery technology', 'Includes prebiotic', 'Sustainable packaging'], ARRAY['Subscription only', 'Premium pricing', 'Only available direct', 'Takes 2-4 weeks for full effects'], 'Science-focused gut health optimizers', true),

('Digestive Daily Probiotic', 'Culturelle', 'culturelle-digestive-daily', 'The #1 clinically studied probiotic brand with Lactobacillus rhamnosus GG, the most researched probiotic strain in the world with over 1,000 studies.', 'Culturelle contains Lactobacillus rhamnosus GG (LGG), the single most researched probiotic strain on earth. With over 1,000 scientific studies and 200+ clinical trials, LGG has the strongest evidence base of any probiotic.', '840cca75-0ebc-44a2-819f-212cd78a1464', 'https://m.media-amazon.com/images/I/71x-qPuRLIL._AC_SL1500_.jpg', 18, 28, 4.6, 'https://www.amazon.com/s?k=Culturelle+Digestive+Daily+Probiotic', NULL, ARRAY['Lactobacillus rhamnosus GG', '10 Billion CFU', 'Inulin Prebiotic'], ARRAY['Most researched probiotic strain', 'Simple one-strain formula', 'Includes inulin prebiotic', 'Very affordable'], ARRAY['Single strain limits diversity', 'Fewer CFU than premium options', 'Needs refrigeration', 'Basic formula vs modern synbiotics'], 'Probiotic beginners wanting research-backed strains', false),

('Probiotic Supplement', 'Align', 'align-probiotic', 'The #1 gastroenterologist-recommended probiotic featuring the unique Bifidobacterium 35624 strain, clinically proven to support digestive balance and IBS symptom relief.', 'Align uses Bifidobacterium longum 35624, a proprietary strain clinically studied in multiple large trials for digestive balance. It is the most recommended probiotic by gastroenterologists in the United States.', '840cca75-0ebc-44a2-819f-212cd78a1464', 'https://m.media-amazon.com/images/I/81OlgSsXlDL._AC_SL1500_.jpg', 25, 40, 4.5, 'https://www.amazon.com/s?k=Align+Probiotic', NULL, ARRAY['Bifidobacterium longum 35624', '1 Billion CFU'], ARRAY['#1 gastroenterologist recommended', 'Clinically proven for IBS symptoms', 'Gentle daily support', 'No refrigeration needed'], ARRAY['Only 1 billion CFU (low count)', 'Single strain', 'Premium price for one strain', 'Capsule format only'], 'IBS sufferers and GI-sensitive individuals', false),

('Dr. Formulated Probiotics', 'Garden of Life', 'garden-of-life-probiotics', 'A 50 billion CFU, 16-strain organic probiotic formulated by a gastroenterologist. Includes clinically studied strains for digestive and immune health.', 'Garden of Life Dr. Formulated Probiotics was created in partnership with Dr. David Perlmutter, a board-certified neurologist. It provides 50 billion CFU from 16 diverse strains with shelf-stable technology.', '840cca75-0ebc-44a2-819f-212cd78a1464', 'https://m.media-amazon.com/images/I/71bfpfuA7kL._AC_SL1500_.jpg', 28, 42, 4.6, 'https://www.amazon.com/s?k=Garden+of+Life+Dr+Formulated+Probiotics', NULL, ARRAY['16 Probiotic Strains', '50 Billion CFU', 'Organic Prebiotic Fiber', 'Shelf Stable'], ARRAY['Doctor formulated', 'High CFU count (50 billion)', 'Organic prebiotic included', 'No refrigeration needed'], ARRAY['Once Daily Mens/Womens specific formulas', 'Large capsule', 'Premium pricing', 'May cause initial bloating'], 'Health-conscious consumers wanting a complete probiotic', true),

('Synbiotic+', 'Ritual', 'ritual-synbiotic-plus', 'A clinically studied 2-in-1 synbiotic with 11 billion CFU of two targeted strains plus a prebiotic, in a delayed-release capsule designed for survival through stomach acid.', 'Ritual brings their signature science-first approach to gut health. Synbiotic+ uses two clinically studied strains (LGG and BB-12), the two most researched probiotics in the world, paired with a prebiotic in a delayed-release mint-tab capsule.', '840cca75-0ebc-44a2-819f-212cd78a1464', 'https://m.media-amazon.com/images/I/61IhBiUX3kL._AC_SL1500_.jpg', 36, 42, 4.5, 'https://www.amazon.com/s?k=Ritual+Synbiotic+Plus', 'https://ritual.com/products/synbiotic-plus', ARRAY['LGG', 'BB-12', '11 Billion CFU', 'PreforPro Prebiotic'], ARRAY['Two most-studied probiotic strains', 'Delayed-release capsule', 'Mint tab keeps it fresh', 'Clean ingredient sourcing'], ARRAY['Subscription model', 'Only 2 strains (less diversity)', 'Premium pricing', 'Lower CFU than some competitors'], 'Modern health-conscious consumers', true);