/*
  # Add New Products - Vitamins, Sleep Aids, Longevity

  1. New Products
    - 5 new Vitamins: Garden of Life Vitamin Code, NOW Adam, Athletic Greens AG1, Kirkland Daily Multi, Life Extension Two-Per-Day
    - 5 new Sleep Aids: Beam Dream, OLLY Sleep, Magnesium L-Threonate (Magtein), Apigenin, Sleep Breakthrough
    - 5 new Longevity: Tru Niagen, Vital Proteins Collagen, Nordic Naturals Omega-3, BioAstin Astaxanthin, Thorne Quercetin
*/

-- New Vitamins & Minerals
INSERT INTO products (name, brand, slug, description, long_description, category_id, image_url, price_min, price_max, rating, affiliate_link, affiliate_link_official, key_ingredients, pros, cons, best_for, third_party_tested) VALUES
('Vitamin Code Men', 'Garden of Life', 'garden-of-life-vitamin-code-men', 'A raw, whole-food multivitamin for men with live probiotics and enzymes. Made from 23 organically grown fruits and vegetables.', 'Garden of Life Vitamin Code is made from RAW whole foods with no synthetic vitamins. It includes live probiotics, enzymes for digestion, and nutrients from 23 organic fruits and vegetables.', '72878b6e-5ff7-48f6-a68a-41f55cb50611', 'https://m.media-amazon.com/images/I/71M1W5SZDKL._AC_SL1500_.jpg', 35, 50, 4.6, 'https://www.amazon.com/s?k=Garden+of+Life+Vitamin+Code+Men', NULL, ARRAY['Whole Food Vitamins', 'Live Probiotics', 'Enzymes', 'Organic Fruits & Vegetables'], ARRAY['RAW whole food sourced', 'Includes probiotics and enzymes', 'Non-GMO Project Verified', 'No synthetic fillers or binders'], ARRAY['4 capsules per day', 'Larger capsule size', 'More expensive than synthetics', 'Must be refrigerated after opening'], 'Men wanting whole-food nutrition', true),

('Adam Superior Men''s Multi', 'NOW Foods', 'now-adam-mens-multi', 'A comprehensive men''s multivitamin with saw palmetto, plant sterols, lycopene, and CoQ10 for prostate and cardiovascular health support.', 'NOW Adam is one of the most complete and affordable men''s multivitamins available. It goes beyond basic vitamins by including saw palmetto for prostate support, plant sterols for cholesterol, and CoQ10 for energy.', '72878b6e-5ff7-48f6-a68a-41f55cb50611', 'https://m.media-amazon.com/images/I/71HPZsw5z0L._AC_SL1500_.jpg', 18, 30, 4.5, 'https://www.amazon.com/s?k=NOW+Adam+Mens+Multi', NULL, ARRAY['Full Vitamin Spectrum', 'Saw Palmetto', 'Plant Sterols', 'Lycopene', 'CoQ10'], ARRAY['Excellent value for money', 'Includes prostate support', 'GMP certified facility', 'Comprehensive formula'], ARRAY['Large softgel size', 'Some synthetic vitamin forms', '2 softgels daily', 'Contains soy'], 'Budget-conscious men', true),

('AG1 Greens Powder', 'Athletic Greens', 'athletic-greens-ag1', 'A comprehensive daily greens powder with 75 vitamins, minerals, probiotics, adaptogens, and whole food sourced nutrients in one scoop.', 'AG1 by Athletic Greens is the most popular greens supplement in the world, used by top podcasters, athletes, and health influencers. One scoop provides a foundational dose of vitamins, minerals, prebiotics, probiotics, adaptogens, and superfoods.', '72878b6e-5ff7-48f6-a68a-41f55cb50611', 'https://m.media-amazon.com/images/I/61e-A0pc3jL._AC_SL1500_.jpg', 79, 99, 4.5, 'https://www.amazon.com/s?k=Athletic+Greens+AG1', 'https://drinkag1.com', ARRAY['75 Vitamins & Minerals', 'Probiotics', 'Adaptogens', 'Superfoods', 'Digestive Enzymes'], ARRAY['All-in-one nutritional insurance', '75 ingredients per scoop', 'Third-party tested', 'Tastes decent for a greens powder'], ARRAY['Very expensive ($3+ per serving)', 'Subscription model preferred', 'Nutrient doses may be low individually', 'Contains some proprietary blends'], 'Health optimizers willing to invest', true),

('Daily Multi', 'Kirkland Signature', 'kirkland-daily-multi', 'Costco''s house-brand comprehensive multivitamin with USP verification and a full spectrum of essential vitamins and minerals at an unbeatable price.', 'Kirkland Signature Daily Multi is the ultimate budget multivitamin. USP Verified for potency and purity, it covers all essential vitamins and minerals at meaningful doses for just pennies per day.', '72878b6e-5ff7-48f6-a68a-41f55cb50611', 'https://m.media-amazon.com/images/I/71dhtgb3GGL._AC_SL1500_.jpg', 10, 18, 4.4, 'https://www.amazon.com/s?k=Kirkland+Signature+Daily+Multi', NULL, ARRAY['Full A-Z Vitamins', 'Iron', 'Calcium', 'Zinc', 'Selenium'], ARRAY['Incredibly affordable (pennies per day)', 'USP Verified', 'Full vitamin spectrum', '500 count bottle lasts over a year'], ARRAY['Basic synthetic forms', 'No probiotics or extras', 'Must have Costco membership', 'Large tablet'], 'Budget shoppers', true),

('Two-Per-Day Capsules', 'Life Extension', 'life-extension-two-per-day', 'A science-optimized multivitamin with bioactive forms at doses significantly higher than typical multivitamins, based on the latest research.', 'Life Extension Two-Per-Day provides dramatically higher potencies than Centrum and other mass-market multivitamins. It uses bioactive forms including 5-MTHF folate, methylcobalamin B12, and mixed tocopherols.', '72878b6e-5ff7-48f6-a68a-41f55cb50611', 'https://m.media-amazon.com/images/I/71Rk5A2CJQL._AC_SL1500_.jpg', 16, 24, 4.6, 'https://www.amazon.com/s?k=Life+Extension+Two-Per-Day', NULL, ARRAY['Bioactive B Vitamins', 'Mixed Tocopherols', 'Zinc Citrate', 'Selenium', 'Chromium', 'Lutein'], ARRAY['High-potency bioactive forms', 'Only 2 capsules daily', 'Excellent value for quality', 'Based on latest research'], ARRAY['No iron (by design)', 'Not whole-food sourced', 'Capsules are moderately large', 'May be excessive for some nutrients'], 'Science-minded supplement users', true);

-- New Sleep Aids
INSERT INTO products (name, brand, slug, description, long_description, category_id, image_url, price_min, price_max, rating, affiliate_link, affiliate_link_official, key_ingredients, pros, cons, best_for, third_party_tested) VALUES
('Dream Powder', 'Beam', 'beam-dream', 'A trendy nano CBD and magnesium sleep powder with reishi, L-theanine, and melatonin in delicious hot cocoa and other dessert flavors.', 'Beam Dream has taken social media by storm with its dessert-flavored sleep powder. It combines nano hemp extract, reishi mushroom, magnesium, L-theanine, and melatonin for a relaxing bedtime ritual.', 'b87c2721-02df-4e49-9929-5abcda05a714', 'https://m.media-amazon.com/images/I/71O5YMwD50L._AC_SL1500_.jpg', 36, 45, 4.5, 'https://www.amazon.com/s?k=Beam+Dream+Sleep+Powder', 'https://www.beamorganics.com/products/dream-powder', ARRAY['Nano Hemp Extract', 'Reishi Mushroom', 'Magnesium', 'L-Theanine', 'Melatonin'], ARRAY['Delicious dessert flavors', 'Enjoyable bedtime ritual', 'Multi-ingredient formula', 'Popular and well-reviewed'], ARRAY['Contains hemp/CBD extract', 'Expensive per serving', 'Added sweeteners', 'Proprietary blend amounts'], 'Social media-savvy wellness consumers', false),

('OLLY Sleep Gummies', 'OLLY', 'olly-sleep-gummies', 'A tasty blackberry-flavored gummy combining melatonin, L-theanine, and botanicals like chamomile and passionflower for gentle sleep support.', 'OLLY Sleep gummies have become one of the best-selling sleep supplements thanks to their candy-like taste and gentle formula. They provide 3mg melatonin with calming L-theanine, chamomile, and passionflower.', 'b87c2721-02df-4e49-9929-5abcda05a714', 'https://m.media-amazon.com/images/I/71VTQ+DdD+L._AC_SL1500_.jpg', 10, 16, 4.4, 'https://www.amazon.com/s?k=OLLY+Sleep+Gummies', NULL, ARRAY['Melatonin 3mg', 'L-Theanine', 'Chamomile', 'Passionflower', 'Lemon Balm'], ARRAY['Tastes like candy', 'Very affordable', 'Gentle low-dose melatonin', 'Available everywhere'], ARRAY['Contains added sugar', 'Lower ingredient doses than capsules', 'Gummy format less precise', 'Not for those avoiding sweeteners'], 'Casual users who want a tasty option', false),

('Magnesium L-Threonate', 'NOW Foods', 'now-magtein', 'The only form of magnesium clinically shown to cross the blood-brain barrier, specifically designed for cognitive function and sleep quality.', 'Magnesium L-Threonate (Magtein) was developed at MIT and is the only magnesium form shown to significantly increase brain magnesium levels. This unique property makes it especially effective for cognitive function and sleep.', 'b87c2721-02df-4e49-9929-5abcda05a714', 'https://m.media-amazon.com/images/I/71BH8r7LxnL._AC_SL1500_.jpg', 20, 35, 4.5, 'https://www.amazon.com/s?k=NOW+Magtein+Magnesium+L-Threonate', NULL, ARRAY['Magnesium L-Threonate (Magtein)', 'Patented Form'], ARRAY['Crosses blood-brain barrier', 'MIT-developed and patented', 'Supports both sleep and cognition', 'Well-tolerated'], ARRAY['3 capsules per serving', 'Lower elemental magnesium per dose', 'More expensive than other mag forms', 'Single mineral only'], 'Those wanting brain-targeted magnesium', true),

('Apigenin 50mg', 'Nootropics Depot', 'nootropics-depot-apigenin', 'A single-ingredient sleep aid featuring apigenin, the flavonoid found in chamomile responsible for its calming effects, at a concentrated 50mg dose.', 'Apigenin is the active compound in chamomile tea that promotes relaxation. Popularized by neuroscientist Andrew Huberman, supplemental apigenin at 50mg provides a much higher dose than tea for meaningful sleep support.', 'b87c2721-02df-4e49-9929-5abcda05a714', 'https://m.media-amazon.com/images/I/71HCVj1a47L._AC_SL1500_.jpg', 15, 22, 4.4, 'https://www.amazon.com/s?k=Apigenin+50mg', NULL, ARRAY['Apigenin 50mg'], ARRAY['Science-backed single ingredient', 'Popularized by Dr. Huberman', 'Non-hormonal sleep support', 'Great for stacking'], ARRAY['Subtle effects for some users', 'Single ingredient only', 'May lower estrogen (caution for women)', 'Limited long-term studies at this dose'], 'Biohackers following Huberman protocol', true),

('Sleep Breakthrough', 'BiOptimizers', 'bioptimizers-sleep-breakthrough', 'A comprehensive sleep drink formula with magnesium bisglycinate, glycine, GABA, pharmaGABA, L-theanine, tart cherry, and more for deep restorative sleep.', 'BiOptimizers Sleep Breakthrough is a premium drink powder designed to support every stage of sleep. It combines bioavailable magnesium, amino acids, and botanicals for faster onset, deeper sleep, and refreshed waking.', 'b87c2721-02df-4e49-9929-5abcda05a714', 'https://m.media-amazon.com/images/I/61RWUZ9aGxL._AC_SL1500_.jpg', 50, 68, 4.5, 'https://www.amazon.com/s?k=BiOptimizers+Sleep+Breakthrough', NULL, ARRAY['Magnesium Bisglycinate', 'Glycine', 'GABA', 'PharmaGABA', 'L-Theanine', 'Tart Cherry'], ARRAY['Comprehensive multi-pathway formula', 'Delicious drink format', 'No melatonin dependency', 'Targets all sleep stages'], ARRAY['Premium pricing', 'Large serving size', 'Only available online', 'Some ingredients in proprietary blend'], 'Those who prefer drink format over pills', false);

-- New Longevity & Anti-Aging
INSERT INTO products (name, brand, slug, description, long_description, category_id, image_url, price_min, price_max, rating, affiliate_link, affiliate_link_official, key_ingredients, pros, cons, best_for, third_party_tested) VALUES
('Tru Niagen', 'ChromaDex', 'tru-niagen', 'A patented nicotinamide riboside (NR) supplement clinically proven to increase NAD+ levels by up to 51%. The only NR with multiple published human clinical trials.', 'Tru Niagen contains Niagen, the only nicotinamide riboside with an FDA new dietary ingredient notification and multiple published clinical trials. It has been shown to safely and effectively increase NAD+ levels.', 'b4111ed1-490c-4446-a9a1-6e869828522b', 'https://m.media-amazon.com/images/I/71-kXf2aDRL._AC_SL1500_.jpg', 40, 52, 4.6, 'https://www.amazon.com/s?k=Tru+Niagen+300mg', NULL, ARRAY['Nicotinamide Riboside 300mg', 'Patented Niagen'], ARRAY['Multiple published clinical trials', 'FDA GRAS status', 'Clinically shown to boost NAD+ 51%', 'Simple one-capsule dose'], ARRAY['Expensive for a single ingredient', 'Effects hard to feel immediately', 'Requires ongoing supplementation', 'No additional synergistic ingredients'], 'Longevity-focused adults over 40', true),

('Collagen Peptides', 'Vital Proteins', 'vital-proteins-collagen', 'The best-selling collagen supplement in America with 20g of grass-fed, pasture-raised collagen peptides per serving for skin, hair, nails, and joint health.', 'Vital Proteins Collagen Peptides is the gold standard in collagen supplementation. Sourced from grass-fed, pasture-raised bovine hides, it provides 20g of types I and III collagen peptides per serving.', 'b4111ed1-490c-4446-a9a1-6e869828522b', 'https://m.media-amazon.com/images/I/61z-ILQMCGL._AC_SL1500_.jpg', 25, 45, 4.7, 'https://www.amazon.com/s?k=Vital+Proteins+Collagen+Peptides', NULL, ARRAY['Type I Collagen', 'Type III Collagen', 'Hyaluronic Acid', 'Vitamin C'], ARRAY['20g collagen per serving', 'Dissolves in hot or cold liquids', 'Grass-fed sourced', 'Noticeable skin and nail improvements'], ARRAY['Bovine-sourced (not vegan)', 'Large scoop size', 'Unflavored can thicken drinks', 'Results take 4-8 weeks'], 'Those prioritizing skin and joint health', true),

('Ultimate Omega', 'Nordic Naturals', 'nordic-naturals-omega-3', 'The #1 selling omega-3 in the US with 1280mg EPA+DHA per serving in triglyceride form for superior absorption. IFOS 5-star certified.', 'Nordic Naturals Ultimate Omega is the gold standard in fish oil supplements. It provides concentrated EPA and DHA in the natural triglyceride form (not ethyl ester), with IFOS 5-star certification for purity and potency.', 'b4111ed1-490c-4446-a9a1-6e869828522b', 'https://m.media-amazon.com/images/I/71aTW8GN4ZL._AC_SL1500_.jpg', 28, 55, 4.7, 'https://www.amazon.com/s?k=Nordic+Naturals+Ultimate+Omega', NULL, ARRAY['EPA 650mg', 'DHA 450mg', 'Triglyceride Form'], ARRAY['Natural triglyceride form (better absorption)', 'IFOS 5-star certified', 'No fishy aftertaste', 'Sustainable sourcing (Friend of the Sea)'], ARRAY['Requires 2 softgels for full dose', 'Premium pricing', 'Softgels are moderately large', 'Must refrigerate after opening'], 'Heart and brain health seekers', true),

('BioAstin Hawaiian Astaxanthin', 'Nutrex Hawaii', 'bioastin-astaxanthin', 'Natural astaxanthin from Hawaiian microalgae, one of the most powerful antioxidants in nature - 6000x stronger than vitamin C in singlet oxygen quenching.', 'BioAstin is the world''s leading natural astaxanthin supplement, cultivated from Haematococcus pluvialis microalgae in Hawaii. Astaxanthin is a carotenoid antioxidant 6000x more potent than vitamin C and 800x stronger than CoQ10.', 'b4111ed1-490c-4446-a9a1-6e869828522b', 'https://m.media-amazon.com/images/I/71r7n5VJsrL._AC_SL1500_.jpg', 18, 30, 4.5, 'https://www.amazon.com/s?k=BioAstin+Astaxanthin+12mg', NULL, ARRAY['Natural Astaxanthin 12mg', 'Hawaiian Microalgae'], ARRAY['Extremely potent antioxidant', 'Supports skin health and UV protection', 'Anti-inflammatory properties', 'Sustainably grown in Hawaii'], ARRAY['Takes 2-4 weeks for noticeable effects', 'Can turn skin slightly orange at high doses', 'Premium vs synthetic astaxanthin', 'Single active ingredient'], 'Skin health and anti-inflammatory seekers', false),

('Quercetin Phytosome', 'Thorne', 'thorne-quercetin', 'A highly bioavailable quercetin using phytosome technology for up to 20x better absorption. Supports immune function, cardiovascular health, and longevity pathways.', 'Thorne Quercetin Phytosome uses Quercefit technology to bind quercetin with sunflower phospholipids, dramatically increasing absorption. Quercetin is a senolytic that helps clear senescent (zombie) cells.', 'b4111ed1-490c-4446-a9a1-6e869828522b', 'https://m.media-amazon.com/images/I/61YqCGjyURL._AC_SL1500_.jpg', 22, 32, 4.5, 'https://www.amazon.com/s?k=Thorne+Quercetin+Phytosome', NULL, ARRAY['Quercetin Phytosome', 'Sunflower Phospholipids'], ARRAY['20x better absorption than standard quercetin', 'Senolytic properties', 'NSF Certified for Sport', 'Supports immune and cardiovascular health'], ARRAY['Capsule-only format', 'Less research than standard quercetin doses', 'Premium pricing for Thorne quality', 'Single ingredient supplement'], 'Longevity enthusiasts and immune support', true);