/*
  # Add Products for Pre-Workout and Creatine Categories

  1. New Products
    - 5 Pre-Workout: Transparent Labs BULK, C4 Original, Pre-Kaged Elite, Ghost Legend, Gorilla Mode
    - 5 Creatine: Thorne Creatine, Transparent Labs Creatine HMB, Optimum Nutrition Micronized, CON-CRET Patented, Naked Creatine
*/

-- Pre-Workout
INSERT INTO products (name, brand, slug, description, long_description, category_id, image_url, price_min, price_max, rating, affiliate_link, affiliate_link_official, key_ingredients, pros, cons, best_for, third_party_tested) VALUES
('BULK Pre-Workout', 'Transparent Labs', 'transparent-labs-bulk', 'A clinically dosed pre-workout with 8g citrulline, 4g beta-alanine, 200mg caffeine, and no artificial sweeteners or colors. The gold standard for clean pre-workouts.', 'Transparent Labs BULK is widely considered the best overall pre-workout supplement. Every single ingredient is clinically dosed and clearly labeled. No proprietary blends, artificial sweeteners, or unnecessary fillers.', '7b1574dc-da98-4206-92bc-5d1a5cc6c7ce', 'https://m.media-amazon.com/images/I/517YwDUwUYL._AC_SL1200_.jpg', 45, 55, 4.8, 'https://www.amazon.com/s?k=Transparent+Labs+BULK+Pre+Workout', 'https://www.transparentlabs.com/products/preseries-bulk-pre-workout', ARRAY['Citrulline Malate 8g', 'Beta-Alanine 4g', 'BetaPure Betaine 2.5g', 'Caffeine 200mg', 'Theanine 200mg'], ARRAY['Fully transparent label', 'Clinical doses of everything', 'No artificial sweeteners', 'Smooth energy without crash'], ARRAY['Premium price point', 'Only available online', 'Some flavors sell out', '200mg caffeine may be mild for stim junkies'], 'Clean pre-workout enthusiasts', true),

('C4 Original', 'Cellucor', 'cellucor-c4-original', 'The world''s best-selling pre-workout with a proven blend of caffeine, beta-alanine, and creatine nitrate for explosive energy, focus, and pumps.', 'Cellucor C4 has been the #1 selling pre-workout for nearly a decade. Its combination of CarnoSyn beta-alanine, caffeine, creatine nitrate, and Nitric Oxide boosters delivers reliable energy and performance.', '7b1574dc-da98-4206-92bc-5d1a5cc6c7ce', 'https://m.media-amazon.com/images/I/71dRXwcWi6L._AC_SL1500_.jpg', 22, 30, 4.6, 'https://www.amazon.com/s?k=Cellucor+C4+Original', NULL, ARRAY['CarnoSyn Beta-Alanine', 'Caffeine 150mg', 'Creatine Nitrate', 'Arginine AKG'], ARRAY['Very affordable', 'Available everywhere', 'Many flavor options', 'Reliable energy boost'], ARRAY['Proprietary blends', 'Under-dosed some key ingredients', 'Contains artificial colors', '150mg caffeine is low for experienced users'], 'Beginners and casual gym-goers', false),

('Pre-Kaged Elite', 'Kaged', 'pre-kaged-elite', 'A premium all-in-one pre-workout with patented ingredients at full clinical doses: 10g citrulline, 3.5g beta-alanine, 3.2g creatine HCl, and caffeine from PurCaf organic coffee bean.', 'Kaged Elite is the flagship pre-workout from one of the most respected supplement brands. Every ingredient uses the patented, premium form and is dosed at or above clinical levels.', '7b1574dc-da98-4206-92bc-5d1a5cc6c7ce', 'https://m.media-amazon.com/images/I/71Fm4FE+VEL._AC_SL1500_.jpg', 45, 55, 4.7, 'https://www.amazon.com/s?k=Pre-Kaged+Elite', NULL, ARRAY['L-Citrulline 10g', 'Beta-Alanine 3.5g', 'Creatine HCl 3.2g', 'PurCaf Caffeine 388mg', 'Alpha-GPC'], ARRAY['Mega-dosed citrulline at 10g', 'Patented premium ingredients', 'Informed Sport certified', 'Includes cognitive enhancers'], ARRAY['Very high caffeine (388mg)', 'Premium price', 'Large scoop size', 'May be too strong for beginners'], 'Experienced athletes wanting maximum performance', true),

('Ghost Legend', 'Ghost', 'ghost-legend', 'A lifestyle pre-workout with iconic candy brand flavor collabs (Sour Patch Kids, Warheads, Swedish Fish), fully transparent label, and solid clinical dosing.', 'Ghost Legend brings the same licensed flavor magic to the pre-workout category. Beyond the fun branding, it delivers genuinely effective doses of citrulline, beta-alanine, and caffeine.', '7b1574dc-da98-4206-92bc-5d1a5cc6c7ce', 'https://m.media-amazon.com/images/I/719FqGnmIuL._AC_SL1500_.jpg', 38, 48, 4.6, 'https://www.amazon.com/s?k=Ghost+Legend+Pre+Workout', NULL, ARRAY['L-Citrulline 4g', 'Beta-Alanine 3.2g', 'Natural Caffeine 250mg', 'Alpha-GPC', 'Senactiv'], ARRAY['Incredible licensed flavors', 'Fully transparent label', 'Solid clinical dosing', 'Smooth energy profile'], ARRAY['Brand premium on pricing', 'Some ingredients could be higher dosed', 'Licensed flavors contain artificial ingredients', '4g citrulline is below optimal'], 'Flavor-focused fitness enthusiasts', false),

('Gorilla Mode', 'Gorilla Mind', 'gorilla-mode', 'A mega-dosed pre-workout with 9g citrulline, 5g creatine, 1500mg GlycerPump, and 350mg caffeine. One of the most stacked formulas on the market.', 'Gorilla Mode from Gorilla Mind is an aggressively dosed pre-workout designed for maximum performance. It combines huge doses of pump agents, strength builders, and stimulants into one formula.', '7b1574dc-da98-4206-92bc-5d1a5cc6c7ce', 'https://m.media-amazon.com/images/I/71KYj2pCinL._AC_SL1500_.jpg', 42, 50, 4.7, 'https://www.amazon.com/s?k=Gorilla+Mode+Pre+Workout', NULL, ARRAY['L-Citrulline 9g', 'Creatine Monohydrate 5g', 'GlycerPump 1.5g', 'Betaine 2.5g', 'Caffeine 350mg', 'L-Tyrosine 1.5g'], ARRAY['One of the most stacked formulas available', 'Huge pump and energy doses', 'Includes full creatine dose', 'Transparent labeling'], ARRAY['Very high stimulant (350mg caffeine)', 'Large 2-scoop serving', 'Only available from Gorilla Mind', 'May cause jitters or anxiety'], 'Advanced lifters wanting maximum intensity', false);

-- Creatine & Performance
INSERT INTO products (name, brand, slug, description, long_description, category_id, image_url, price_min, price_max, rating, affiliate_link, affiliate_link_official, key_ingredients, pros, cons, best_for, third_party_tested) VALUES
('Creatine Monohydrate', 'Thorne', 'thorne-creatine', 'NSF Certified for Sport creatine monohydrate from the most trusted practitioner brand. Micronized for superior mixability and absorption.', 'Thorne Creatine is the professional athlete''s choice for creatine supplementation. NSF Certified for Sport ensures it is free of banned substances, while micronization ensures easy mixing and gentle digestion.', '5258a865-7c17-417a-b895-4b8ea76d178d', 'https://m.media-amazon.com/images/I/61A3QAdOB9L._AC_SL1500_.jpg', 28, 40, 4.8, 'https://www.amazon.com/s?k=Thorne+Creatine+Monohydrate', NULL, ARRAY['Creatine Monohydrate 5g'], ARRAY['NSF Certified for Sport', 'Trusted by pro athletes', 'Micronized for easy mixing', 'No fillers or additives'], ARRAY['Premium price for creatine', 'Only unflavored', 'Smaller container size', 'Single ingredient only'], 'Professional and competitive athletes', true),

('Creatine HMB', 'Transparent Labs', 'transparent-labs-creatine-hmb', 'A synergistic combination of 5g creatine monohydrate, 2g HMB, and 5mg BioPerine for enhanced strength, muscle preservation, and absorption.', 'Transparent Labs Creatine HMB combines the two most research-backed muscle performance ingredients: creatine for strength and HMB for muscle preservation, with BioPerine for enhanced absorption.', '5258a865-7c17-417a-b895-4b8ea76d178d', 'https://m.media-amazon.com/images/I/51BNVK-g-SL._AC_SL1200_.jpg', 35, 42, 4.7, 'https://www.amazon.com/s?k=Transparent+Labs+Creatine+HMB', 'https://www.transparentlabs.com/products/creatine-hmb', ARRAY['Creatine Monohydrate 5g', 'HMB 2g', 'BioPerine 5mg', 'Vitamin D3'], ARRAY['Creatine + HMB synergy', 'Added Vitamin D3', 'BioPerine for absorption', 'Flavored options available'], ARRAY['More expensive than plain creatine', 'Some may not need HMB', 'Flavored versions contain sweeteners', 'Only available online'], 'Those wanting creatine plus muscle preservation', true),

('Micronized Creatine Powder', 'Optimum Nutrition', 'on-micronized-creatine', 'The best-selling creatine powder with Creapure (German-made) micronized creatine monohydrate. 5g per serving, unflavored, and ultra-pure.', 'Optimum Nutrition Micronized Creatine uses Creapure, the gold standard in creatine manufacturing from Germany. Each batch is tested for purity and potency, delivering 5g of ultra-fine creatine per serving.', '5258a865-7c17-417a-b895-4b8ea76d178d', 'https://m.media-amazon.com/images/I/61MjNX1ydyL._AC_SL1500_.jpg', 15, 30, 4.7, 'https://www.amazon.com/s?k=Optimum+Nutrition+Micronized+Creatine', NULL, ARRAY['Creapure Creatine Monohydrate 5g'], ARRAY['Creapure premium sourcing', 'Incredibly affordable per serving', 'Best-selling creatine worldwide', 'Mixes easily and dissolves well'], ARRAY['Unflavored only', 'No additional ingredients', 'Must scoop and measure', 'Large container can clump'], 'Anyone wanting reliable pure creatine', true),

('Patented Creatine HCl', 'CON-CRET', 'con-cret-creatine-hcl', 'A concentrated creatine hydrochloride requiring only 750mg per serving (vs 5g monohydrate). No loading phase, no bloating, no water retention.', 'CON-CRET uses creatine hydrochloride (HCl), which is 59x more soluble than monohydrate. The increased solubility means a much smaller dose (750mg vs 5g) with no loading phase and virtually no bloating.', '5258a865-7c17-417a-b895-4b8ea76d178d', 'https://m.media-amazon.com/images/I/71-FaMnAF-L._AC_SL1500_.jpg', 22, 30, 4.4, 'https://www.amazon.com/s?k=CON-CRET+Creatine+HCl', NULL, ARRAY['Creatine HCl 750mg', 'Patented Formula'], ARRAY['Micro-dose (no 5g scoops)', 'No loading phase needed', 'No bloating or water retention', 'Easy on the stomach'], ARRAY['Less research than monohydrate', 'More expensive per gram of creatine', 'May be less effective overall', 'Some question HCl vs monohydrate claims'], 'Those who get bloated from monohydrate', false),

('Naked Creatine', 'Naked Nutrition', 'naked-creatine', 'Pure, single-ingredient creatine monohydrate sourced from Germany. No additives, no fillers, no artificial ingredients - just pure creatine.', 'Naked Creatine is exactly what the name implies: pure creatine monohydrate with nothing else. Sourced from a cGMP-certified facility in Germany, it provides 5g of creatine per serving in its simplest form.', '5258a865-7c17-417a-b895-4b8ea76d178d', 'https://m.media-amazon.com/images/I/51W0nZHDxjL._AC_SL1500_.jpg', 20, 32, 4.6, 'https://www.amazon.com/s?k=Naked+Creatine+Monohydrate', NULL, ARRAY['Creatine Monohydrate 5g'], ARRAY['Zero additives or fillers', 'German-sourced creatine', 'Vegan-friendly', 'Very affordable per serving'], ARRAY['Unflavored only', 'No Creapure branding', 'Large tub size only', 'Basic product with no extras'], 'Minimalists and clean-label seekers', true);