/*
  # Add New Products - Nootropics, Protein Powder, Fat Burners

  1. New Products
    - 5 new Nootropics: Hunter Focus, Genius Mushrooms, Prevagen, Neuriva Plus, Real Mushrooms Lions Mane
    - 5 new Protein Powders: Transparent Labs Whey, Naked Whey, Garden of Life Sport, Ghost Whey, Vega Sport
    - 5 new Fat Burners: Transparent Labs PhysiqueSeries, Burn Lab Pro, Jacked Factory Burn-XT, Cellucor SuperHD, Animal Cuts

  2. Notes
    - Products table already has RLS enabled
    - Rankings to be added in separate migration
*/

-- New Nootropics
INSERT INTO products (name, brand, slug, description, long_description, category_id, image_url, price_min, price_max, rating, affiliate_link, affiliate_link_official, key_ingredients, pros, cons, best_for, third_party_tested) VALUES
('Hunter Focus', 'Roar Ambition', 'hunter-focus', 'A premium nootropic designed for high-performing professionals with clinical doses across 20 active ingredients targeting focus, mood, and memory.', 'Hunter Focus is positioned as a premium all-in-one nootropic for executives and professionals. It combines acetylcholine boosters, adaptogenic herbs, and amino acids in generous doses.', 'c59aa68a-ca79-416a-bc07-470b339a07ac', 'https://m.media-amazon.com/images/I/61vXe7LKXAL._AC_SL1500_.jpg', 75, 90, 4.6, 'https://www.amazon.com/s?k=Hunter+Focus+Nootropic', NULL, ARRAY['Citicoline', 'Lion''s Mane', 'Ashwagandha', 'Bacopa Monnieri', 'Phosphatidylserine'], ARRAY['Clinical doses of all ingredients', 'Includes mood and stress support', 'No proprietary blends', 'Premium ingredient quality'], ARRAY['Expensive monthly cost', 'Large capsule size', '6 capsules per day'], 'Professionals & executives', true),

('Genius Mushrooms', 'The Genius Brand', 'genius-mushrooms', 'A stimulant-free nootropic featuring a potent trio of organic Lion''s Mane, Reishi, and Cordyceps mushrooms for cognitive and immune support.', 'Genius Mushrooms harnesses the power of three adaptogenic fungi. Lion''s Mane supports nerve growth factor, Reishi modulates stress response, and Cordyceps boosts cellular energy production.', 'c59aa68a-ca79-416a-bc07-470b339a07ac', 'https://m.media-amazon.com/images/I/61K8V5FSJSL._AC_SL1200_.jpg', 18, 24, 4.5, 'https://www.amazon.com/s?k=Genius+Mushrooms', NULL, ARRAY['Lion''s Mane', 'Reishi', 'Cordyceps'], ARRAY['Very affordable', 'Stimulant-free and natural', 'Well-researched mushroom trio', 'Immune system benefits'], ARRAY['Fewer ingredients than comprehensive nootropics', 'Effects take 2-4 weeks to build', 'No choline source included'], 'Mushroom enthusiasts & budget-conscious', false),

('Prevagen', 'Quincy Bioscience', 'prevagen', 'A memory-focused supplement featuring apoaequorin, a protein originally derived from jellyfish, marketed primarily toward older adults for age-related memory support.', 'Prevagen has become one of the best-selling memory supplements in pharmacies nationwide. Its active ingredient apoaequorin is a calcium-binding protein that may support brain cell function.', 'c59aa68a-ca79-416a-bc07-470b339a07ac', 'https://m.media-amazon.com/images/I/61r6bSKKG4L._AC_SL1000_.jpg', 25, 60, 4.2, 'https://www.amazon.com/s?k=Prevagen', NULL, ARRAY['Apoaequorin', 'Vitamin D3'], ARRAY['Widely available in pharmacies', 'Simple one-pill formula', 'Strong brand recognition', 'Gentle with no stimulants'], ARRAY['Limited clinical evidence for apoaequorin', 'Expensive for single ingredient', 'FTC has questioned marketing claims', 'Fewer ingredients than competitors'], 'Older adults seeking memory support', false),

('Neuriva Plus', 'Reckitt', 'neuriva-plus', 'A brain performance supplement combining clinically tested Neurofactor coffee cherry extract with phosphatidylserine, B vitamins, and folic acid.', 'Neuriva Plus is one of the most marketed brain supplements in America, leveraging Neurofactor (whole coffee fruit concentrate) to boost BDNF levels while phosphatidylserine supports cell membrane health.', 'c59aa68a-ca79-416a-bc07-470b339a07ac', 'https://m.media-amazon.com/images/I/71O5n0zqRtL._AC_SL1500_.jpg', 28, 40, 4.3, 'https://www.amazon.com/s?k=Neuriva+Plus', NULL, ARRAY['Neurofactor Coffee Cherry', 'Phosphatidylserine', 'B6', 'B12', 'Folic Acid'], ARRAY['Widely available retail', 'Clinically tested Neurofactor', 'Decaffeinated formula', 'Simple daily capsule'], ARRAY['Limited to a few active ingredients', 'Premium price for basic formula', 'BDNF claims need more research', 'No choline or racetam compounds'], 'Mainstream consumers new to nootropics', false),

('Lion''s Mane Mushroom', 'Real Mushrooms', 'real-mushrooms-lions-mane', 'A high-potency Lion''s Mane extract standardized to beta-glucans, using only the fruiting body for maximum nerve growth factor support.', 'Real Mushrooms sets the standard for mushroom supplements by using only organic fruiting body extracts (no mycelium-on-grain fillers). Their Lion''s Mane is standardized to over 25% beta-glucans.', 'c59aa68a-ca79-416a-bc07-470b339a07ac', 'https://m.media-amazon.com/images/I/71YB3kQQ7GL._AC_SL1500_.jpg', 25, 32, 4.6, 'https://www.amazon.com/s?k=Real+Mushrooms+Lions+Mane', NULL, ARRAY['Lion''s Mane Fruiting Body', 'Beta-Glucans >25%'], ARRAY['Fruiting body only (no filler)', 'Standardized beta-glucan content', 'USDA Organic certified', 'Excellent for stacking'], ARRAY['Single ingredient only', 'Takes weeks for noticeable effects', 'Earthy taste if using powder'], 'Biohackers & mushroom supplement purists', true);

-- New Protein Powders
INSERT INTO products (name, brand, slug, description, long_description, category_id, image_url, price_min, price_max, rating, affiliate_link, affiliate_link_official, key_ingredients, pros, cons, best_for, third_party_tested) VALUES
('100% Grass-Fed Whey', 'Transparent Labs', 'transparent-labs-whey', 'A clean-label grass-fed whey isolate with 28g protein per scoop, zero artificial sweeteners, and only natural flavoring. Informed Sport certified.', 'Transparent Labs has built a reputation on radical ingredient transparency. Their 100% Grass-Fed Whey uses whey from pasture-raised, grass-fed cows with no artificial colors, sweeteners, or preservatives.', '25195943-0811-47f0-ba92-50d103c363d7', 'https://m.media-amazon.com/images/I/51oiB2QujnL._AC_SL1200_.jpg', 50, 60, 4.8, 'https://www.amazon.com/s?k=Transparent+Labs+Whey+Protein', 'https://www.transparentlabs.com/products/proteinseries-100-grass-fed-whey-protein-isolate', ARRAY['Grass-Fed Whey Isolate', 'Natural Sweeteners', 'No Artificial Colors'], ARRAY['28g protein per scoop', 'Grass-fed sourcing', 'No artificial anything', 'Informed Sport certified'], ARRAY['Higher price than conventional whey', 'Limited store availability', 'Some flavors sell out quickly'], 'Clean-label and health-conscious athletes', true),

('Naked Whey', 'Naked Nutrition', 'naked-whey', 'Stripped-down grass-fed whey protein with only one ingredient: 100% whey protein concentrate from US farms. No additives, fillers, or sweeteners.', 'Naked Whey is the minimalist choice. The unflavored version literally contains one ingredient: grass-fed whey protein concentrate sourced from small US dairy farms. Nothing else.', '25195943-0811-47f0-ba92-50d103c363d7', 'https://m.media-amazon.com/images/I/41hTQUTJg3L._AC_SL1500_.jpg', 35, 90, 4.6, 'https://www.amazon.com/s?k=Naked+Whey+Protein', NULL, ARRAY['Grass-Fed Whey Concentrate', 'No Additives'], ARRAY['Only 1 ingredient (unflavored)', 'Cold-processed to preserve nutrients', 'No artificial sweeteners or GMOs', 'Excellent for baking and recipes'], ARRAY['Unflavored version is bland', 'Concentrate not isolate (more fat/carbs)', 'Large 5lb bag only option', 'Mixes less smoothly than isolates'], 'Minimalists who want zero additives', true),

('Sport Organic Plant-Based', 'Garden of Life', 'garden-of-life-sport', 'A USDA Organic, NSF Certified for Sport plant protein with 30g per serving from pea, sprouted navy bean, lentil, and cranberry seed proteins.', 'Garden of Life Sport Organic combines five plant protein sources to deliver a complete amino acid profile with 30g per serving. USDA Organic, Non-GMO, NSF Certified for Sport, and Informed Choice certified.', '25195943-0811-47f0-ba92-50d103c363d7', 'https://m.media-amazon.com/images/I/819pOqDpeDL._AC_SL1500_.jpg', 38, 50, 4.5, 'https://www.amazon.com/s?k=Garden+of+Life+Sport+Organic+Protein', NULL, ARRAY['Organic Pea Protein', 'Sprouted Navy Bean', 'Lentil Protein', 'Cranberry Seed', 'Tart Cherry'], ARRAY['30g plant protein per serving', 'NSF Certified for Sport', 'USDA Organic', 'Added tart cherry for recovery'], ARRAY['Slightly gritty texture', 'Higher price than conventional plant protein', 'Strong flavor may not suit all'], 'Organic-focused vegan athletes', true),

('Ghost Whey Protein', 'Ghost', 'ghost-whey', 'A lifestyle protein brand featuring authentic flavor collaborations with brands like Oreo, Nutter Butter, and Chips Ahoy. 25g of a whey blend per scoop.', 'Ghost has disrupted the supplement industry with their transparent labeling and licensed flavor collaborations. Ghost Whey uses a blend of whey isolate, concentrate, and hydrolysate.', '25195943-0811-47f0-ba92-50d103c363d7', 'https://m.media-amazon.com/images/I/619t+N7q5DL._AC_SL1500_.jpg', 40, 50, 4.7, 'https://www.amazon.com/s?k=Ghost+Whey+Protein', NULL, ARRAY['Whey Protein Isolate', 'Whey Concentrate', 'Whey Hydrolysate', 'Digestive Enzymes'], ARRAY['Incredible licensed flavors (Oreo, Chips Ahoy)', 'Fully transparent label', '25g protein per scoop', 'Added digestive enzymes'], ARRAY['Brand-name flavors contain artificial ingredients', 'Blend not pure isolate', 'Pricier than basic options', 'Some flavors very sweet'], 'Flavor-focused fitness enthusiasts', false),

('Vega Sport Premium', 'Vega', 'vega-sport-premium', 'A performance-driven plant protein with 30g protein from pea, pumpkin seed, sunflower seed, and alfalfa, plus tart cherry and probiotics.', 'Vega Sport Premium is designed for serious athletes who want plant-based nutrition. 30g protein per serving with added BCAAs, glutamine, tart cherry for recovery, and 1 billion CFU probiotics.', '25195943-0811-47f0-ba92-50d103c363d7', 'https://m.media-amazon.com/images/I/718-WT0mxmL._AC_SL1500_.jpg', 42, 55, 4.5, 'https://www.amazon.com/s?k=Vega+Sport+Premium+Protein', NULL, ARRAY['Pea Protein', 'Pumpkin Seed', 'Sunflower Seed', 'Tart Cherry', 'Probiotics'], ARRAY['30g plant protein', 'Added probiotics and tart cherry', 'NSF Certified for Sport', 'No artificial flavors'], ARRAY['Premium pricing', 'Texture can be chalky', 'Stevia flavor not for everyone', 'Large scoop size'], 'Competitive plant-based athletes', true);

-- New Fat Burners
INSERT INTO products (name, brand, slug, description, long_description, category_id, image_url, price_min, price_max, rating, affiliate_link, affiliate_link_official, key_ingredients, pros, cons, best_for, third_party_tested) VALUES
('PhysiqueSeries Fat Burner', 'Transparent Labs', 'transparent-labs-fat-burner', 'A science-backed thermogenic with clinically dosed forslean, green tea extract, and synephrine. No proprietary blends, every dose visible on the label.', 'Transparent Labs PhysiqueSeries takes the same radical transparency approach to fat burning. Every ingredient is clinically dosed and clearly listed, with research citations for each.', '60bc620a-e02a-4f8f-aba0-e925330378ef', 'https://m.media-amazon.com/images/I/51YEMTv1mBL._AC_SL1500_.jpg', 45, 55, 4.6, 'https://www.amazon.com/s?k=Transparent+Labs+Fat+Burner', 'https://www.transparentlabs.com/products/physiqueseries-fat-burner', ARRAY['Forslean (Forskolin)', 'Green Tea Extract', 'Synephrine', '5-HTP', 'L-Tyrosine'], ARRAY['Fully transparent dosing', 'Clinically backed ingredients', 'Includes mood support (5-HTP)', 'No proprietary blends'], ARRAY['Contains synephrine (stimulant)', 'Premium price point', '4 capsules per serving', 'Limited flavor options'], 'Evidence-based fitness enthusiasts', true),

('Burn Lab Pro', 'Opti Nutra', 'burn-lab-pro', 'A stimulant-free fat burner using forslean, HMB, capsimax, and chromium to support fat loss while preserving lean muscle mass.', 'Burn Lab Pro takes an innovative stim-free approach to fat burning. By combining Forslean for fat release, HMB for muscle preservation, and Capsimax for calorie burning, it supports body recomposition without jitters.', '60bc620a-e02a-4f8f-aba0-e925330378ef', 'https://m.media-amazon.com/images/I/51zzRlLhx2L._AC_SL1020_.jpg', 45, 55, 4.5, 'https://www.amazon.com/s?k=Burn+Lab+Pro', NULL, ARRAY['Forslean', 'HMB', 'Capsimax', 'Chromium', 'BioPerine'], ARRAY['100% stimulant-free', 'Preserves muscle while burning fat', 'Clean label (no additives)', 'Can be taken any time of day'], ARRAY['Slower results than stim-based burners', 'Premium pricing', 'Only available online', 'Requires consistent use for results'], 'Those sensitive to stimulants', true),

('Burn-XT', 'Jacked Factory', 'jacked-factory-burn-xt', 'A no-frills thermogenic fat burner with straightforward ingredients at research doses. Best-selling fat burner on Amazon with thousands of reviews.', 'Jacked Factory Burn-XT keeps it simple: proven ingredients, honest dosing, and an affordable price. Its combination of acetyl L-carnitine, green tea extract, and caffeine hits the core fat-burning pathways.', '60bc620a-e02a-4f8f-aba0-e925330378ef', 'https://m.media-amazon.com/images/I/610OWaVCIWL._AC_SL1500_.jpg', 20, 28, 4.5, 'https://www.amazon.com/s?k=Jacked+Factory+Burn-XT', NULL, ARRAY['Acetyl L-Carnitine', 'Green Tea Extract', 'Caffeine Anhydrous', 'Capsimax', 'BioPerine'], ARRAY['Very affordable', 'Amazon best-seller', 'Simple effective formula', 'Good dose of ALCAR for energy'], ARRAY['Contains caffeine (270mg)', 'Basic formula lacking advanced ingredients', 'May cause jitters in sensitive people', 'Large capsules'], 'Budget-conscious dieters', false),

('SuperHD', 'Cellucor', 'cellucor-superhd', 'A two-stage fat burner combining thermogenic ingredients with nootropic focus enhancers for energized, focused training during a cut.', 'Cellucor SuperHD combines traditional fat-burning ingredients with cognitive enhancers for a dual-purpose supplement that supports both physical and mental performance during caloric restriction.', '60bc620a-e02a-4f8f-aba0-e925330378ef', 'https://m.media-amazon.com/images/I/71eVKQAVTFL._AC_SL1500_.jpg', 22, 30, 4.3, 'https://www.amazon.com/s?k=Cellucor+SuperHD', NULL, ARRAY['Caffeine', 'Green Tea Extract', 'Capsimax', 'Amla Fruit Extract', 'Dandelion'], ARRAY['Combines fat burning with focus', 'Affordable pricing', 'Well-known trusted brand', 'Available in stores everywhere'], ARRAY['Uses proprietary blends', 'Moderate caffeine content', 'Not as potent as premium options', 'Some fillers in formula'], 'Gym-goers wanting energy and fat loss', false),

('Animal Cuts', 'Universal Nutrition', 'animal-cuts', 'A comprehensive thermogenic pack with 8 targeted complexes covering every angle of contest-prep fat loss: thermogenic, metabolic, thyroid, water shedding, and more.', 'Animal Cuts is the bodybuilder''s choice for serious pre-contest cutting. Each serving is a pack of multiple pills covering thermogenic, metabolic, thyroid, nootropic, cortisol, CCK, water shedding, and bioavailability complexes.', '60bc620a-e02a-4f8f-aba0-e925330378ef', 'https://m.media-amazon.com/images/I/81ZJDRoFEnL._AC_SL1500_.jpg', 32, 42, 4.4, 'https://www.amazon.com/s?k=Animal+Cuts', NULL, ARRAY['Caffeine', 'Green Tea', 'Oolong Tea', 'Dandelion Root', 'Uva Ursi', 'Juniper Berry'], ARRAY['Most comprehensive fat loss formula', 'Covers 8 different pathways', 'Trusted bodybuilding brand', 'Effective water shedding'], ARRAY['Very high pill count per serving', 'Not for beginners', 'Contains multiple stimulants', 'Proprietary blend amounts'], 'Competitive bodybuilders', false);